#! /bin/sh

sxhkd &
polybar example &
dunst &
xsetroot -cursor_name left_ptr
$HOME/.fehbg


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a wenlin.exe state=floating
bspc rule -a simplescreenrecorder state=floating
